feat(client-cli): WIP: first sketch of authentication
Does not compile because I have a generic type constraint to a trait
which has only one implementation (minisign::SecretKey):

    error[E0308]: mismatched types
   --> client-cli/src/utils.rs:185:56
    |
172 | pub fn create_auth_headers<MSK>(payload: &str, secret_key: SecretKey<MSK>) -> Result<HeaderMap>
    |                            --- found this type parameter
...
185 |     let auth_signature = AuthSignature::new(auth_info, secret_key)
    |                          ------------------            ^^^^^^^^^^ expected `SecretKey<SecretKey>`, found `SecretKey<MSK>`
    |                          |
    |                          arguments to this function are incorrect
    |
    = note: expected struct `features_lib::SecretKey<minisign::SecretKey>`
               found struct `features_lib::SecretKey<MSK>`
note: associated function defined here
   --> /home/dotdev/gits/asfaload/asfasign/rest_api_auth/src/lib.rs:78:12
    |
 78 |     pub fn new(auth_info: AuthInfo, secret_key: SecretKey<MSK>) -> Result<Self, AuthError>
    |            ^^^